# Generated by Django 4.2.4 on 2023-09-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='contactnum',
            new_name='contactno',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='enquiry',
            new_name='enquirytext',
        ),
    ]
