# Generated by Django 4.2.4 on 2023-09-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0002_rename_contactnum_enquiry_contactno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='redate',
            new_name='regdate',
        ),
    ]
