# Generated by Django 4.2.4 on 2023-09-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_rename_redate_student_regdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
